[versions]
agp = "8.13.1"
kotlin = "2.2.10"
kotlinKsp = "2.2.10-2.0.2" # KSP 版本的前一部分必须与 build 中使用的 Kotlin 版本一致
activityCompose = "1.12.1"
composeBom = "2025.12.00"
okhttpBom = "5.3.2"
retrofit = "3.0.0"
hilt = "2.57.2"
cameraView = "1.5.2"
nav3Core = "1.0.0"
lifecycleViewmodelNav3 = "2.10.0"

[libraries]
# gradle plugins
zxing = { module = "com.google.zxing:core", version = "3.5.4" }
gradle = { module = "com.android.tools.build:gradle", version = "8.13.1" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Android core libraries
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.10.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
material = { module = "com.google.android.material:material", version = "1.13.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }

# Compose libraries
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
# https://developer.android.google.cn/jetpack/androidx/releases/compose-material3?hl=zh-cn
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version = "1.10.0" }

# Navigation libraries
# https://developer.android.google.cn/guide/navigation/navigation-3/get-started?hl=zh_cn
# Core Navigation 3 libraries
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-material3-adaptive-navigation3 = { module = "androidx.compose.material3.adaptive:adaptive-navigation3", version = "1.3.0-alpha02" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.3.0" }

# UI utilities
# https://developer.android.google.cn/develop/ui/views/launch/splash-screen/migrate?hl=zh-cn
# https://developer.android.google.cn/jetpack/androidx/releases/core?hl=zh-cn
androidx-core-splash = { module = "androidx.core:core-splashscreen", version = "1.2.0" }
# https://developer.android.google.cn/topic/libraries/app-startup?hl=zh-cn
# https://developer.android.google.cn/jetpack/androidx/releases/startup?hl=zh-cn
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }

# Network libraries
# https://github.com/square/okhttp?tab=readme-ov-file#releases
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
# https://github.com/square/retrofit#download
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

# Dependency injection
# https://developer.android.google.cn/training/dependency-injection/hilt-android?hl=zh-cn
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-ksp = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# Camera libraries
# https://developer.android.google.cn/jetpack/androidx/releases/camera?hl=zh_cn
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
androidx-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraView" }

# Data storage
# https://developer.android.google.cn/topic/libraries/architecture/datastore?hl=zh-cn
# https://developer.android.google.cn/jetpack/androidx/releases/datastore?hl=zh_cn#kts
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.2.0" }

# ML Kit
# https://google-developers.gonglchuangl.net/ml-kit/release-notes
# https://google-developers.gonglchuangl.net/ml-kit/vision/barcode-scanning/android?hl=zh-cn
mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version = "17.3.0" }

# Kotlin extensions
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.10.2" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }

# Testing libraries
junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }

# https://github.com/google/gson
gson = { module = "com.google.code.gson:gson", version = "2.13.2" }

munch1182-lib = { module = "com.munch1182.android:lib", version = "0.1.0" }
munch1182-bluetooth = { module = "com.munch1182.android:bluetooth", version = "0.1.0" }
munch1182-scan = { module = "com.munch1182.android:scan", version = "0.1.0" }
munch1182-weight = { module = "com.munch1182.android:weight", version = "0.1.0" }
munch1182-net = { module = "com.munch1182.android:net", version = "0.1.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android.plugin", version.ref = "hilt" }
# Optional plugins
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.21" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version = "2.57.2" }
# https://developer.android.google.cn/build/migrate-to-ksp?hl=zh-cn
# https://kotlinlang.org/docs/ksp-quickstart.html
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }